
class Response():
    def json_response():
        r_json = {
        'moon_phase': {
            'moonset': {'minute': '14', 'hour': '0'},
            'hemisphere': 'North',
            'moonrise': {'minute': '55', 'hour': '10'},
            'percentIlluminated': '33',
            'sunset': {'minute': '10', 'hour': '20'},
            'current_time': {'minute': '28', 'hour': '21'},
            'sunrise': {'minute': '12', 'hour': '6'},
            'ageOfMoon': '6',
            'phaseofMoon': 'Waxing Crescent'
            },

        'sun_phase': {
            'sunset': {'minute': '10', 'hour': '20'},
            'sunrise': {'minute': '12', 'hour': '6'}
            },

        'query_zone': '041',

        'current_observation': {
            'windchill_f': 'NA',
            'precip_today_string': '0.00 in (0.0 mm)',
            'temperature_string': '74 F (23 C)',
            'visibility_mi': '10.0',
            'temp_f': 74,
            'heat_index_string': 'NA', 'UV': '0',
            'observation_time_rfc822': 'Wed, 11 May 2016 20:51:00 -0400',
            'wind_degrees': 0,
            'solarradiation': '--',
            'display_location': {
                'latitude': '35.80359268',
                'zip': '27607',
                'state_name': 'North Carolina',
                'country_iso3166': 'US',
                'full': 'Raleigh, NC',
                'elevation': '119.00000000',
                'wmo': '99999',
                'state': 'NC',
                'city': 'Raleigh',
                'country': 'US',
                'longitude': '-78.69741058',
                'magic':'1'
                },
            'image': {
                'link': 'http://www.wunderground.com',
                'title': 'Weather Underground',
                'url': 'http://icons.wxug.com/graphics/wu2/logo_130x80.png'
                },
            'feelslike_string': '74 F (23 C)',
            'wind_string': 'Calm',
            'precip_1hr_metric': '--',
            'wind_gust_kph': 0,
            'precip_today_metric': '0.0',
            'estimated': {},
            'local_time_rfc822': 'Wed, 11 May 2016 21:28:00 -0400',
            'feelslike_f': '74',
            'windchill_c': 'NA',
            'observation_location': {
                'elevation': '436 ft',
                'latitude': '35.89223099',
                'state': 'North Carolina',
                'city': 'Raleigh-Durham Airport',
                'country_iso3166': 'US',
                'country': 'US',
                'longitude': '-78.78185272',
                'full': 'Raleigh-Durham Airport, North Carolina'
                },
            'forecast_url': 'http://www.wunderground.com/US/NC/Raleigh.html',
            'ob_url': 'http://www.wunderground.com/cgi-bin/findweather/getForecast?query=35.89223099,-78.78185272',
            'heat_index_f': 'NA',
            'precip_1hr_in': '-9999.00',
            'local_tz_short': 'EDT',
            'precip_today_in': '0.00',
            'windchill_string': 'NA',
            'icon_url': 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
            'wind_kph': 0,
            'wind_mph': 0,
            'dewpoint_string': '67 F (19 C)',
            'local_tz_offset': '-0400',
            'observation_time': 'Last Updated on May 11, 8:51 PM EDT',
            'icon': 'partlycloudy',
            'heat_index_c': 'NA',
            'feelslike_c': '23',
            'wind_dir': 'North',
            'history_url': 'http://www.wunderground.com/history/airport/KRDU/2016/5/11/DailyHistory.html',
            'visibility_km': '16.1',
            'relative_humidity': '79%',
            'dewpoint_f': 67,
            'pressure_mb': '1018',
            'temp_c': 23,
            'wind_gust_mph': 0,
            'local_tz_long': 'America/New_York',
            'weather': 'Partly Cloudy',
            'pressure_trend': '+',
            'nowcast': '',
            'local_epoch': '1463016480',
            'pressure_in': '30.07',
            'dewpoint_c': 19,
            'precip_1hr_string': '-9999.00 in (-9999.00 mm)',
            'observation_epoch': '1463014260',
            'station_id': 'KRDU'
            },

        'alerts': [],

        'response': {
            'version': '0.1',
            'error': {'type': 'unknownfeature'},
            'features': {
                'astronomy': 1,
                'conditions': 1,
                'currenthurricane': 1,
                'forecast10day': 1,
                'alerts': 1
                },
            'termsofService': 'http://www.wunderground.com/weather/api/d/terms.html'
            },

        'currenthurricane': [],

        'forecast': {
            'simpleforecast': {
                'forecastday': [
                    {
                    'low': {'celsius': '18', 'fahrenheit': '64'},
                    'icon_url': 'http://icons.wxug.com/i/c/k/mostlycloudy.gif',
                    'minhumidity': 0,
                    'maxhumidity': 0,
                    'maxwind': {'mph': 5, 'dir': '', 'degrees': 0, 'kph': 8},
                    'snow_night': {'in': 0.0, 'cm': 0.0},
                    'avehumidity': 90,
                    'icon': 'mostlycloudy',
                    'pop': 20,
                    'skyicon': '',
                    'qpf_night': {'in': 0.0, 'mm': 0},
                    'high': {'celsius': '28', 'fahrenheit': '83'},
                    'conditions': 'Mostly Cloudy',
                    'qpf_allday': {'in': 0.0, 'mm': 0},
                    'period': 1,
                    'date': {
                        'isdst': '1',
                        'tz_short': 'EDT',
                        'hour': 19,
                        'yday': 131,
                        'weekday_short': 'Wed',
                        'epoch': '1463007600',
                        'day': 11,
                        'weekday': 'Wednesday',
                        'year': 2016,
                        'tz_long': 'America/New_York',
                        'month': 5,
                        'monthname': 'May',
                        'pretty': '7:00 PM EDT on May 11, 2016',
                        'monthname_short': 'May',
                        'sec': 0,
                        'ampm': 'PM',
                        'min': '00'
                        },
                    'snow_day': {'in': None, 'cm': None},
                    'qpf_day': {'in': None, 'mm': None},
                    'avewind': {'mph': 0, 'dir': 'South', 'degrees': 180, 'kph': 0},
                    'snow_allday': {'in': 0.0, 'cm': 0.0}
                    },
                    {
                    'low': {'celsius': '19', 'fahrenheit': '67'},
                    'icon_url': 'http://icons.wxug.com/i/c/k/cloudy.gif',
                    'minhumidity': 0,
                    'maxhumidity': 0,
                    'maxwind': {'mph': 5, 'dir': 'ENE', 'degrees': 60, 'kph': 8},
                    'snow_night': {'in': 0.0, 'cm': 0.0},
                    'avehumidity': 73,
                    'icon': 'cloudy',
                    'pop': 20,
                    'skyicon': '',
                    'qpf_night': {
                        'in': 0.05,
                        'mm': 1
                        },
                    'high': {'celsius': '28', 'fahrenheit': '83'},
                    'conditions': 'Overcast',
                    'qpf_allday': {'in': 0.05, 'mm': 1},
                    'period': 2,
                    'date': {
                        'isdst': '1',
                        'tz_short': 'EDT',
                        'hour': 19,
                        'yday': 132,
                        'weekday_short': 'Thu',
                        'epoch': '1463094000',
                        'day': 12,
                        'weekday': 'Thursday',
                        'year': 2016,
                        'tz_long': 'America/New_York',
                        'month': 5,
                        'monthname': 'May',
                        'pretty': '7:00 PM EDT on May 12, 2016',
                        'monthname_short': 'May',
                        'sec': 0,
                        'ampm': 'PM',
                        'min': '00'
                        },
                    'snow_day': {'in': 0.0, 'cm': 0.0},
                    'qpf_day': {'in': 0.0, 'mm': 0},
                    'avewind': {'mph': 4, 'dir': 'ENE', 'degrees': 60, 'kph': 6},
                    'snow_allday': {'in': 0.0, 'cm': 0.0}
                    },
                    {
                    'low': {'celsius': '15', 'fahrenheit': '59'},
                    'icon_url': 'http://icons.wxug.com/i/c/k/chancetstorms.gif',
                    'minhumidity': 0,
                    'maxhumidity': 0,
                    'maxwind': {'mph': 10, 'dir': 'WSW', 'degrees': 255, 'kph': 16},
                    'snow_night': {'in': 0.0, 'cm': 0.0},
                    'avehumidity': 71,
                    'icon': 'chancetstorms',
                    'pop': 60,
                    'skyicon': '',
                    'qpf_night': {'in': 0.0, 'mm': 0},
                    'high': {'celsius': '26', 'fahrenheit': '78'},
                    'conditions': 'Chance of a Thunderstorm',
                    'qpf_allday': {'in': 0.19, 'mm': 5},
                    'period': 3,
                    'date': {
                        'isdst': '1',
                        'tz_short': 'EDT',
                        'hour': 19,
                        'yday': 133,
                        'weekday_short': 'Fri',
                        'epoch': '1463180400',
                        'day': 13,
                        'weekday': 'Friday',
                        'year': 2016,
                        'tz_long': 'America/New_York',
                        'month': 5,
                        'monthname': 'May',
                        'pretty': '7:00 PM EDT on May 13, 2016',
                        'monthname_short': 'May',
                        'sec': 0,
                        'ampm': 'PM',
                        'min': '00'
                        },
                    'snow_day': {'in': 0.0, 'cm': 0.0},
                    'qpf_day': {'in': 0.19, 'mm': 5},
                    'avewind': {'mph': 8, 'dir': 'WSW', 'degrees': 255, 'kph': 13},
                    'snow_allday': {'in': 0.0, 'cm': 0.0}
                    },
                    {
                    'low': {'celsius': '11', 'fahrenheit': '52'},
                    'icon_url': 'http://icons.wxug.com/i/c/k/partlycloudy.gif',
                    'minhumidity': 0,
                    'maxhumidity': 0,
                    'maxwind': {'mph': 15, 'dir': 'W', 'degrees': 262, 'kph': 24},
                    'snow_night': {'in': 0.0, 'cm': 0.0},
                    'avehumidity': 49,
                    'icon': 'partlycloudy',
                    'pop': 20,
                    'skyicon': '',
                    'qpf_night': {'in': 0.0, 'mm': 0},
                    'high': {'celsius': '28', 'fahrenheit': '83'},
                    'conditions': 'Partly Cloudy',
                    'qpf_allday': {'in': 0.0, 'mm': 0},
                    'period': 4,
                    'date': {
                        'isdst': '1',
                        'tz_short': 'EDT',
                        'hour': 19,
                        'yday': 134,
                        'weekday_short': 'Sat',
                        'epoch': '1463266800',
                        'day': 14,
                        'weekday': 'Saturday',
                        'year': 2016,
                        'tz_long': 'America/New_York',
                        'month': 5,
                        'monthname': 'May',
                        'pretty': '7:00 PM EDT on May 14, 2016',
                        'monthname_short': 'May',
                        'sec': 0,
                        'ampm': 'PM',
                        'min': '00'
                        },
                    'snow_day': {'in': 0.0, 'cm': 0.0},
                    'qpf_day': {'in': 0.0, 'mm': 0},
                    'avewind': {'mph': 12, 'dir': 'W', 'degrees': 262, 'kph': 19},
                    'snow_allday': {'in': 0.0, 'cm': 0.0}
                    },
                    {
                    'low': {'celsius': '12', 'fahrenheit': '53'},
                    'icon_url': 'http://icons.wxug.com/i/c/k/clear.gif',
                    'minhumidity': 0,
                    'maxhumidity': 0,
                    'maxwind': {'mph': 10, 'dir': 'WNW', 'degrees': 290, 'kph': 16},
                    'snow_night': {'in': 0.0, 'cm': 0.0},
                    'avehumidity': 43,
                    'icon': 'clear',
                    'pop': 0,
                    'skyicon': '',
                    'qpf_night': {'in': 0.0, 'mm': 0},
                    'high': {'celsius': '22', 'fahrenheit': '72'},
                    'conditions': 'Clear',
                    'qpf_allday': {'in': 0.0, 'mm': 0},
                    'period': 5,
                    'date': {
                        'isdst': '1',
                        'tz_short': 'EDT',
                        'hour': 19,
                        'yday': 135,
                        'weekday_short': 'Sun',
                        'epoch': '1463353200',
                        'day': 15,
                        'weekday': 'Sunday',
                        'year': 2016,
                        'tz_long': 'America/New_York',
                        'month': 5,
                        'monthname': 'May',
                        'pretty': '7:00 PM EDT on May 15, 2016',
                        'monthname_short': 'May',
                        'sec': 0,
                        'ampm': 'PM',
                        'min': '00'
                        },
                    'snow_day': {'in': 0.0, 'cm': 0.0},
                    'qpf_day': {'in': 0.0, 'mm': 0},
                    'avewind': {'mph': 8, 'dir': 'WNW', 'degrees': 290, 'kph': 13},
                    'snow_allday': {'in': 0.0, 'cm': 0.0}
                    },
                    {
                    'low': {'celsius': '14', 'fahrenheit': '58'},
                    'icon_url': 'http://icons.wxug.com/i/c/k/partlycloudy.gif',
                    'minhumidity': 0,
                    'maxhumidity': 0,
                    'maxwind': {'mph': 5, 'dir': 'E', 'degrees': 89, 'kph': 8},
                    'snow_night': {'in': 0.0, 'cm': 0.0},
                    'avehumidity': 41,
                    'icon': 'partlycloudy',
                    'pop': 0,
                    'skyicon': '',
                    'qpf_night': {'in': 0.0, 'mm': 0},
                    'high': {'celsius': '23', 'fahrenheit': '73'},
                    'conditions': 'Partly Cloudy',
                    'qpf_allday': {'in': 0.0, 'mm': 0},
                    'period': 6,
                    'date': {
                        'isdst': '1',
                        'tz_short': 'EDT',
                        'hour': 19,
                        'yday': 136,
                        'weekday_short': 'Mon',
                        'epoch': '1463439600',
                        'day': 16,
                        'weekday': 'Monday',
                        'year': 2016,
                        'tz_long': 'America/New_York',
                        'month': 5,
                        'monthname': 'May',
                        'pretty': '7:00 PM EDT on May 16, 2016',
                        'monthname_short': 'May',
                        'sec': 0,
                        'ampm': 'PM',
                        'min': '00'
                        },
                    'snow_day': {'in': 0.0, 'cm': 0.0},
                    'qpf_day': {'in': 0.0, 'mm': 0},
                    'avewind': {'mph': 4, 'dir': 'E', 'degrees': 89, 'kph': 6},
                    'snow_allday': {'in': 0.0, 'cm': 0.0}
                    },
                    {
                    'low': {'celsius': '19', 'fahrenheit': '66'},
                    'icon_url': 'http://icons.wxug.com/i/c/k/chancerain.gif',
                    'minhumidity': 0,
                    'maxhumidity': 0,
                    'maxwind': {'mph': 10, 'dir': 'SE', 'degrees': 128, 'kph': 16},
                    'snow_night': {'in': 0.0, 'cm': 0.0},
                    'avehumidity': 60,
                    'icon': 'chancerain',
                    'pop': 50,
                    'skyicon': '',
                    'qpf_night': {'in': 0.13, 'mm': 3},
                    'high': {'celsius': '26', 'fahrenheit': '78'},
                    'conditions': 'Chance of Rain',
                    'qpf_allday': {'in': 0.22, 'mm': 6},
                    'period': 7,
                    'date': {
                        'isdst': '1',
                        'tz_short': 'EDT',
                        'hour': 19,
                        'yday': 137,
                        'weekday_short': 'Tue',
                        'epoch': '1463526000',
                        'day': 17,
                        'weekday': 'Tuesday',
                        'year': 2016,
                        'tz_long': 'America/New_York',
                        'month': 5,
                        'monthname': 'May',
                        'pretty': '7:00 PM EDT on May 17, 2016',
                        'monthname_short': 'May',
                        'sec': 0,
                        'ampm': 'PM',
                        'min': '00'
                        },
                    'snow_day': {'in': 0.0, 'cm': 0.0},
                    'qpf_day': {'in': 0.09, 'mm': 2},
                    'avewind': {'mph': 6, 'dir': 'SE', 'degrees': 128, 'kph': 10},
                    'snow_allday': {'in': 0.0, 'cm': 0.0}
                    },
                    {
                    'low': {'celsius': '19', 'fahrenheit': '67'},
                    'icon_url': 'http://icons.wxug.com/i/c/k/chancetstorms.gif',
                    'minhumidity': 0,
                    'maxhumidity': 0,
                    'maxwind': {'mph': 15, 'dir': 'SW', 'degrees': 215, 'kph': 24},
                    'snow_night': {'in': 0.0, 'cm': 0.0},
                    'avehumidity': 70,
                    'icon': 'chancetstorms',
                    'pop': 40,
                    'skyicon': '',
                    'qpf_night': {'in': 0.1, 'mm': 3},
                    'high': {'celsius': '28', 'fahrenheit': '82'},
                    'conditions': 'Chance of a Thunderstorm',
                    'qpf_allday': {'in': 0.11, 'mm': 3},
                    'period': 8,
                    'date': {
                        'isdst': '1',
                        'tz_short': 'EDT',
                        'hour': 19,
                        'yday': 138,
                        'weekday_short': 'Wed',
                        'epoch': '1463612400',
                        'day': 18,
                        'weekday': 'Wednesday',
                        'year': 2016,
                        'tz_long': 'America/New_York',
                        'month': 5,
                        'monthname': 'May',
                        'pretty': '7:00 PM EDT on May 18, 2016',
                        'monthname_short': 'May',
                        'sec': 0,
                        'ampm': 'PM',
                        'min': '00'
                        },
                    'snow_day': {'in': 0.0, 'cm': 0.0},
                    'qpf_day': {'in': 0.01, 'mm': 0},
                    'avewind': {'mph': 10, 'dir': 'SW', 'degrees': 215, 'kph': 16},
                    'snow_allday': {'in': 0.0, 'cm': 0.0}
                    },
                    {
                    'low': {'celsius': '19', 'fahrenheit': '67'},
                    'icon_url': 'http://icons.wxug.com/i/c/k/chancetstorms.gif',
                    'minhumidity': 0,
                    'maxhumidity': 0,
                    'maxwind': {'mph': 10, 'dir': 'SW', 'degrees': 218, 'kph': 16},
                    'snow_night': {'in': 0.0, 'cm': 0.0},
                    'avehumidity': 75,
                    'icon': 'chancetstorms',
                    'pop': 60,
                    'skyicon': '',
                    'qpf_night': {'in': 0.09, 'mm': 2},
                    'high': {'celsius': '27', 'fahrenheit': '81'},
                    'conditions': 'Chance of a Thunderstorm',
                    'qpf_allday': {'in': 0.24, 'mm': 6},
                    'period': 9,
                    'date': {
                        'isdst': '1',
                        'tz_short': 'EDT',
                        'hour': 19,
                        'yday': 139,
                        'weekday_short': 'Thu',
                        'epoch': '1463698800',
                        'day': 19,
                        'weekday': 'Thursday',
                        'year': 2016,
                        'tz_long': 'America/New_York',
                        'month': 5,
                        'monthname': 'May',
                        'pretty': '7:00 PM EDT on May 19, 2016',
                        'monthname_short': 'May',
                        'sec': 0,
                        'ampm': 'PM',
                        'min': '00'
                        },
                    'snow_day': {'in': 0.0, 'cm': 0.0},
                    'qpf_day': {'in': 0.15, 'mm': 4},
                    'avewind': {'mph': 8, 'dir': 'SW', 'degrees': 218, 'kph': 13},
                    'snow_allday': {'in': 0.0, 'cm': 0.0}
                    },
                    {
                    'low': {'celsius': '18', 'fahrenheit': '65'},
                    'icon_url': 'http://icons.wxug.com/i/c/k/chancerain.gif',
                    'minhumidity': 0,
                    'maxhumidity': 0,
                    'maxwind': {'mph': 10, 'dir': 'WSW', 'degrees': 246, 'kph': 16},
                    'snow_night': {'in': 0.0, 'cm': 0.0},
                    'avehumidity': 72,
                    'icon': 'chancerain',
                    'pop': 30,
                    'skyicon': '',
                    'qpf_night': {'in': 0.17, 'mm': 4},
                    'high': {'celsius': '27', 'fahrenheit': '80'},
                    'conditions': 'Chance of Rain',
                    'qpf_allday': {'in': 0.19, 'mm': 5},
                    'period': 10,
                    'date': {
                        'isdst': '1',
                        'tz_short': 'EDT',
                        'hour': 19,
                        'yday': 140,
                        'weekday_short': 'Fri',
                        'epoch': '1463785200',
                        'day': 20,
                        'weekday': 'Friday',
                        'year': 2016,
                        'tz_long': 'America/New_York',
                        'month': 5,
                        'monthname': 'May',
                        'pretty': '7:00 PM EDT on May 20, 2016',
                        'monthname_short': 'May',
                        'sec': 0,
                        'ampm': 'PM',
                        'min': '00'
                        },
                    'snow_day': {'in': 0.0, 'cm': 0.0},
                    'qpf_day': {'in': 0.01, 'mm': 0},
                    'avewind': {'mph': 8, 'dir': 'WSW', 'degrees': 246, 'kph': 13},
                    'snow_allday': {'in': 0.0, 'cm': 0.0}
                    }
                ]
            },

        'txt_forecast': {
            'forecastday': [
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/mostlycloudy.gif',
                'period': 0,
                'fcttext_metric': 'Considerable cloudiness. Low 18C.',
                'title': 'Wednesday',
                'icon': 'mostlycloudy',
                'pop': '20',
                'fcttext': 'Mainly cloudy. Lows overnight in the mid 60s.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif',
                'period': 1,
                'fcttext_metric': 'Mainly cloudy. A stray shower or thunderstorm is possible. Low 18C. Winds light and variable.',
                'title': 'Wednesday Night',
                'icon': 'nt_mostlycloudy',
                'pop': '20',
                'fcttext': 'Mostly cloudy. A stray shower or thunderstorm is possible. Low 64F. Winds light and variable.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/cloudy.gif',
                'period': 2,
                'fcttext_metric': 'Cloudy. A stray shower or thunderstorm is possible. High 28C. Winds light and variable.',
                'title': 'Thursday',
                'icon': 'cloudy',
                'pop': '20',
                'fcttext': 'Cloudy skies. A stray shower or thunderstorm is possible. High 83F. Winds light and variable.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/nt_chancetstorms.gif',
                'period': 3,
                'fcttext_metric': 'Scattered showers and thunderstorms. Low 19C. Winds light and variable. Chance of rain 50%.',
                'title': 'Thursday Night',
                'icon': 'nt_chancetstorms',
                'pop': '40',
                'fcttext': 'Partly to mostly cloudy skies with scattered thunderstorms mainly before midnight. Low 67F. Winds light and variable. Chance of rain 40%.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/chancetstorms.gif',
                'period': 4,
                'fcttext_metric': 'Thunderstorms likely. High around 25C. Winds WSW at 10 to 15 km/h. Chance of rain 80%.',
                'title': 'Friday',
                'icon': 'chancetstorms',
                'pop': '60',
                'fcttext': 'Mixed clouds and sun with scattered thunderstorms. High 78F. Winds WSW at 5 to 10 mph. Chance of rain 60%.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
                'period': 5,
                'fcttext_metric': 'Partly cloudy skies. Low around 15C. Winds light and variable.',
                'title': 'Friday Night',
                'icon': 'nt_partlycloudy',
                'pop': '0',
                'fcttext': 'Partly cloudy skies. Low 59F. Winds light and variable.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/partlycloudy.gif',
                'period': 6,
                'fcttext_metric': 'Partly cloudy. A stray shower or thunderstorm is possible. High 28C. Winds W at 15 to 25 km/h.',
                'title': 'Saturday',
                'icon': 'partlycloudy',
                'pop': '20',
                'fcttext': 'Partly cloudy skies. A stray shower or thunderstorm is possible. High 83F. Winds W at 10 to 15 mph.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
                'period': 7,
                'fcttext_metric': 'Partly cloudy skies. Low 11C. Winds NW at 10 to 15 km/h.',
                'title': 'Saturday Night',
                'icon': 'nt_partlycloudy',
                'pop': '0',
                'fcttext': 'Some clouds early will give way to generally clear conditions overnight. Low 52F. Winds NW at 5 to 10 mph.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/clear.gif',
                'period': 8,
                'fcttext_metric': 'Mainly sunny. High 22C. Winds WNW at 10 to 15 km/h.',
                'title': 'Sunday',
                'icon': 'clear',
                'pop': '0',
                'fcttext': 'Sunny. High 72F. Winds WNW at 5 to 10 mph.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/nt_clear.gif',
                'period': 9,
                'fcttext_metric': 'Clear to partly cloudy. Low 12C. Winds light and variable.',
                'title': 'Sunday Night',
                'icon': 'nt_clear',
                'pop': '0',
                'fcttext': 'Mainly clear early, then a few clouds later on. Low 53F. Winds light and variable.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/partlycloudy.gif',
                'period': 10,
                'fcttext_metric': 'Sunshine and clouds mixed. High 23C. Winds light and variable.',
                'title': 'Monday',
                'icon': 'partlycloudy',
                'pop': '0',
                'fcttext': 'Sunshine and clouds mixed. High 73F. Winds light and variable.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/nt_clear.gif',
                'period': 11,
                'fcttext_metric': 'Clear skies with a few passing clouds. Low 14C. Winds light and variable.',
                'title': 'Monday Night',
                'icon': 'nt_clear',
                'pop': '10',
                'fcttext': 'Generally fair. Low 58F. Winds light and variable.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/chancerain.gif',
                'period': 12,
                'fcttext_metric': 'Overcast with showers at times. High 26C. Winds SE at 10 to 15 km/h. Chance of rain 50%.',
                'title': 'Tuesday',
                'icon': 'chancerain',
                'pop': '50',
                'fcttext': 'Overcast with showers at times. High 78F. Winds SE at 5 to 10 mph. Chance of rain 50%.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/nt_chancerain.gif',
                'period': 13,
                'fcttext_metric': 'Considerable cloudiness with occasional rain showers. Thunder possible. Low 18C. Winds light and variable. Chance of rain 60%.',
                'title': 'Tuesday Night',
                'icon': 'nt_chancerain',
                'pop': '60',
                'fcttext': 'Overcast with rain showers at times. Thunder possible. Low 66F. Winds light and variable. Chance of rain 60%.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/chancetstorms.gif',
                'period': 14,
                'fcttext_metric': 'Partly to mostly cloudy skies with scattered thunderstorms in the morning. High 28C. Winds SW at 15 to 25 km/h. Chance of rain 40%.',
                'title': 'Wednesday',
                'icon': 'chancetstorms',
                'pop': '40',
                'fcttext': 'Partly to mostly cloudy skies with scattered thunderstorms in the morning. High 82F. Winds SW at 10 to 15 mph. Chance of rain 40%.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/nt_chancerain.gif',
                'period': 15,
                'fcttext_metric': 'Partly cloudy skies early will give way to occasional showers later during the night. Low 19C. Winds S at 10 to 15 km/h. Chance of rain 60%.',
                'title': 'Wednesday Night',
                'icon': 'nt_chancerain',
                'pop': '60',
                'fcttext': 'Partly cloudy skies early followed by increasing clouds with showers developing later at night. Low 67F. Winds S at 5 to 10 mph. Chance of rain 60%.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/chancetstorms.gif',
                'period': 16,
                'fcttext_metric': 'Scattered thunderstorms. High 27C. Winds SW at 10 to 15 km/h. Chance of rain 60%.',
                'title': 'Thursday',
                'icon': 'chancetstorms',
                'pop': '60',
                'fcttext': 'Mixed clouds and sun with scattered thunderstorms. High 81F. Winds SW at 5 to 10 mph. Chance of rain 60%.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/nt_chancetstorms.gif',
                'period': 17,
                'fcttext_metric': 'Scattered thunderstorms in the evening with a few showers possible late. Low 19C. Winds SSW at 10 to 15 km/h. Chance of rain 50%.',
                'title': 'Thursday Night',
                'icon': 'nt_chancetstorms',
                'pop': '50',
                'fcttext': 'Scattered thunderstorms during the evening followed by a few showers overnight. Low 67F. Winds SSW at 5 to 10 mph. Chance of rain 50%.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/chancerain.gif',
                'period': 18,
                'fcttext_metric': 'A shower or two around the area in the morning, then partly cloudy in the afternoon. High 27C. Winds WSW at 10 to 15 km/h. Chance of rain 30%.',
                'title': 'Friday',
                'icon': 'chancerain',
                'pop': '30',
                'fcttext': 'A shower or two around the area in the morning, then partly cloudy in the afternoon. High near 80F. Winds WSW at 5 to 10 mph. Chance of rain 30%.'
                },
                {
                'icon_url': 'http://icons.wxug.com/i/c/k/nt_chancetstorms.gif',
                'period': 19,
                'fcttext_metric': 'Scattered thunderstorms. Low 18C. Winds light and variable. Chance of rain 60%.',
                'title': 'Friday Night',
                'icon': 'nt_chancetstorms',
                'pop': '60',
                'fcttext': 'Variable clouds with scattered thunderstorms. Low near 65F. Winds light and variable. Chance of rain 60%.'
                }
            ],

        'date': '8:07 PM EDT'}
        }
        }
        return r_json
